CUDA_VISIBLE_DEVICES=0 python main_e2e_qp.py \
    --quant_model_path /home/exp_results/efficient_qat/block_ap/Llama-2-7b-w3g128-real \
    --model_family Llama-2 \
    --wbits 3 \
    --group_size 128 \
    --learning_rate 1e-5 \
    --dataset redpajama \
    --dataset_format pt \
    --output_dir /home/exp_results/efficient_qat/e2e-qp-output/Llama-2-7b-w3g128-real-qp \
    --do_train True \
    --pt_context_len 4096 \
    --per_device_train_batch_size 4 \
    --per_device_eval_batch_size 4 \
    --gradient_accumulation_steps 8 \
    --logging_steps 1 \
    --save_strategy epoch \
    --training_strategy epochs \
    --evaluation_strategy steps \
    --eval_steps 64 \
    --max_train_samples 4096 \
    --num_train_epochs 1 \
    --eval_dataset_size 64 \
    --bf16 \
    --data_seed 42 \
    --max_grad_norm 0.3 \
    --preprocessing_num_workers 32